INSERT INTO Product (name, price, createdAt, updatedAt) VALUES
('Laptop Pro X1', 1299.99, datetime('now'), datetime('now')),
('Wireless Headphones Elite', 199.99, datetime('now'), datetime('now')),
('Smart Watch Series 5', 299.99, datetime('now'), datetime('now')),
('4K Gaming Monitor', 499.99, datetime('now'), datetime('now')),
('Mechanical Keyboard RGB', 129.99, datetime('now'), datetime('now')),
('Gaming Mouse Pro', 79.99, datetime('now'), datetime('now')),
('USB-C Hub 8-in-1', 45.99, datetime('now'), datetime('now')),
('External SSD 1TB', 159.99, datetime('now'), datetime('now')),
('Wireless Charger Pad', 29.99, datetime('now'), datetime('now')),
('Bluetooth Speaker XL', 89.99, datetime('now'), datetime('now')),
('Webcam HD 1080p', 69.99, datetime('now'), datetime('now')),
('Graphics Card RTX', 799.99, datetime('now'), datetime('now')),
('RAM 32GB Kit', 149.99, datetime('now'), datetime('now')),
('CPU Cooler RGB', 89.99, datetime('now'), datetime('now')),
('PC Case ATX', 119.99, datetime('now'), datetime('now')),
('Power Supply 750W', 129.99, datetime('now'), datetime('now')),
('Gaming Chair Deluxe', 249.99, datetime('now'), datetime('now')),
('Microphone USB Pro', 139.99, datetime('now'), datetime('now')),
('Camera DSLR Kit', 899.99, datetime('now'), datetime('now')),
('Tablet Pro 12"', 649.99, datetime('now'), datetime('now')),
('Phone Holder Stand', 19.99, datetime('now'), datetime('now')),
('Cable Management Kit', 24.99, datetime('now'), datetime('now')),
('LED Strip Lights', 34.99, datetime('now'), datetime('now')),
('Network Router AC', 159.99, datetime('now'), datetime('now')),
('Wireless Mouse', 39.99, datetime('now'), datetime('now')),
('Desk Pad XL', 29.99, datetime('now'), datetime('now')),
('Monitor Stand', 49.99, datetime('now'), datetime('now')),
('Laptop Cooling Pad', 39.99, datetime('now'), datetime('now')),
('Keyboard Wrist Rest', 19.99, datetime('now'), datetime('now')),
('USB Flash Drive 128GB', 29.99, datetime('now'), datetime('now')),
('Screen Protector Pack', 14.99, datetime('now'), datetime('now')),
('Laptop Sleeve 15"', 24.99, datetime('now'), datetime('now')),
('Cable Ties 50pk', 9.99, datetime('now'), datetime('now')),
('Thermal Paste Pro', 12.99, datetime('now'), datetime('now')),
('Fan Controller RGB', 59.99, datetime('now'), datetime('now')),
('HDMI Cable 4K', 19.99, datetime('now'), datetime('now')),
('Surge Protector', 29.99, datetime('now'), datetime('now')),
('Webcam Cover 3pk', 7.99, datetime('now'), datetime('now')),
('Mouse Bungee', 15.99, datetime('now'), datetime('now')),
('Gaming Glasses', 45.99, datetime('now'), datetime('now')),
('Desk Cable Grommet', 8.99, datetime('now'), datetime('now')),
('Laptop Dock Station', 189.99, datetime('now'), datetime('now')),
('NVMe SSD 500GB', 129.99, datetime('now'), datetime('now')),
('Wi-Fi Extender Pro', 79.99, datetime('now'), datetime('now')),
('Gaming Mousepad', 24.99, datetime('now'), datetime('now')),
('USB Sound Card', 34.99, datetime('now'), datetime('now')),
('Cable Sleeve Kit', 19.99, datetime('now'), datetime('now')),
('Desk Mounted USB Hub', 49.99, datetime('now'), datetime('now')),
('Bluetooth Adapter 5.0', 15.99, datetime('now'), datetime('now')),
('Laptop Power Bank', 89.99, datetime('now'), datetime('now')); 